### PR TITLE
Adding a Demo for the GitHub content and Article View

### PR DESCRIPTION
**Pull request by 1point618**
Edit: First draft is completed. Can be reviewed on Wheelhouse here:

https://wheelhouse-curriculum.herokuapp.com/events/uUIlvrtDVqijP98WhY3a

Would love feedback on the content @johnpaulashenfelter @PeterBell.

### CODE REVIEW

**Comment by 1point618** [comment]
OK, I made some updates and uploaded them to our staging server.

https://wheelhouse-curriculum.herokuapp.com/events/Zxneyn_HmQypAMWO8u9c/

There is no lab yet for the PR, and no text for the Recap, but everything else is in first draft. 

Personally I think we might want to move some of the stuff in the PR article into the Recap, but not sure what yet.

Any feedback appreciated @PeterBell

**Comment by 1point618** [comment]
https://wheelhouse-curriculum.herokuapp.com/events/uUIlvrtDVqijP98WhY3a

@PeterBell @johnpaulashenfelter @chowdhury

This is now in official "first draft" stage. All the labs are done, all the content is written. Would love people's feedback.

**Comment by PeterBell** [comment]
Going through this now @1point618

**Comment by 1point618** [comment]
:+1: Thanks

**Comment by PeterBell** [comment]
One comment - on screen 20 https://wheelhouse-curriculum.herokuapp.com/events/uUIlvrtDVqijP98WhY3a/screens/20 I'm seeing:

screen shot 2015-12-08 at 2 39 06 pm

Note that it says I haven't "created a branch" for a bunch of the steps, but that is the wrong message and indeed isn't the message in your code here - https://github.com/1point618/curriculum-github/blob/demo/modules/DEMO-pull-requests.yml

Mind double checking what's up and if necessary pinging JP if it appears to be a bug?

**Comment by PeterBell** [comment]
I'm also not getting confirmation that I've made the line level commit on that screen even though I have. Not sure if it's old version of content running on server or whether it's a bug . . . mind checking @1point618 ?

**Comment by PeterBell** [comment]
Seeing the same "wrong incomplete text display" on the demo outro - again the code appears OK but not sure if it's what is running on the server - https://github.com/1point618/curriculum-github/blob/demo/modules/DEMO-outro.yml

screen shot 2015-12-08 at 2 44 20 pm

**Comment by PeterBell** [comment]
Also seeing incorrect "success" messages . . .

screen shot 2015-12-08 at 2 46 23 pm

**Comment by PeterBell** [comment]
OK @1point618 I've uploaded some edits to copy - want to check them out and feel free to undo anything you don't like.

Other than tech issue above, only main thought is I think it might be good to try having all of the activities on the next screen - so you read, click to next screen and then have a clean screen with just the labs. Let me know what you think - happy to chat/share thinking.

**Comment by johnpaulashenfelter** [comment]
@PeterBell are you positive that there were no verifications _before_ you started? If you've done this class before (or one with same courseID that was overwritten by newer content on an import) all sorts of surprises can happen in the data.

@1point618 once the class is close to done, I'd suggest letting me restore a production database copy and running the data import from there to make sure things will be clean. 

There's no inherent reason that the payload processing would suddenly break -- most likely reason for this is junky data.

**Comment by 1point618** [comment]
Or I did something incorrect on that particular validation, copied the name
wrong or something.

On Wednesday, December 9, 2015, John Paul Ashenfelter <
notifications@github.com> wrote:

> @PeterBell https://github.com/PeterBell are you positive that there
> were no verifications _before_ you started? If you've done this class
> before (or one with same courseID that was overwritten by newer content on
> an import) all sorts of surprises can happen in the data.
> 
> @1point618 https://github.com/1point618 once the class is close to
> done, I'd suggest letting me restore a production database copy and running
> the data import from there to make sure things will be clean.
> 
> There's no inherent reason that the payload processing would suddenly
> break -- most likely reason for this is junky data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/1point618/curriculum-github/pull/10#issuecomment-163282021
> .

## 

Sent from my pocket computer's glass keyboard.

**Comment by PeterBell** [comment]
It was a clean run through - I'll let @1point618 check it out, let's reimport once the two of you are good with it, I'll do a final test and then try to get it to Cynthia this afternoon so we can start getting their input on pulling down the free course.

**Comment by 1point618** [comment]
Like all of your changes @PeterBell !

**Comment by 1point618** [comment]
OK so I went through everything. All the validations are working, Peter's changes are solid, so I'm going to merge this into master then submit a PR to our main course.

**Pull request merged**
